### ISSUE TITLE
Add README instructions for adding in Mapbox token

### ISSUE THREAD

**Issue by rjnn** [BenMusch/nycguessr#7]
Currently fails with:
```
Uncaught Error: An API access token is required to use Mapbox GL. See https://docs.mapbox.com/api/overview/#access-tokens-and-token-scopes
    at t.RequestManager._makeAPIURL (mapbox.js:213:1)
    at t.RequestManager.normalizeSourceURL (mapbox.js:104:1)
    at F (load_tilejson.js:37:1)
    at Ie.load (vector_tile_source.js:109:1)
    at Ie.onAdd (vector_tile_source.js:144:1)
    at Qt.addSource (style.js:748:1)
    at Qt._load (style.js:310:1)
    at style.js:277:1
```

(happy to pick this one off at a later date)

**Comment by BenMuschol-at** [comment]
Fixed, ty!
