### ISSUE TITLE
dev build fails due to missing SENTRY TOKEN

### ISSUE THREAD

**Issue by rjnn** [BenMusch/nycguessr#8]
This should probably be loaded in optionally based on a set parameter, or skipped if unset.

Failure console error right now:

```
Uncaught SentryError: Invalid Sentry Dsn: %REACT_APP_SENTRY_DSN%
    at dsnFromString (dsn.ts:39:1)
    at makeDsn (dsn.ts:105:1)
    at new BaseClient (baseclient.ts:116:1)
    at new BrowserClient (client.ts:61:1)
    at initAndBind (sdk.ts:33:1)
    at init (sdk.ts:128:1)
    at Module.init (sdk.ts:19:1)
    at ./src/App.tsx (App.tsx:18:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
```

**Comment by BenMusch** [comment]
Resolved! Thanks for reporting
